obj-m += testdriver.o

all:	
	gcc userapp_1.c -o userapp_1; gcc userapp_2.c -o userapp_2; gcc userapp_3.c -o userapp_3; gcc userapp_4.c -o userapp_4 -pthread

clean:
	rm userapp_1; rm userapp_2; rm userapp_3; rm userapp_4
